version: '3.7'

services:
  lambda:
    build: ./lambda
    volumes:
      - ./lambda:/app

  state:
    build:
      args:
        TERRAFORM_VERSION: ${TERRAFORM_VERSION}
      context: ./state
    volumes:
      - ${AWS_CREDENTIALS_PATH}:/root/.aws

  terraform:
    build:
      args:
        FOLDER: ${FOLDER}
        TERRAFORM_VERSION: ${TERRAFORM_VERSION}
      context: .
    volumes:
      - ${AWS_CREDENTIALS_PATH}:/root/.aws
