version: '3.7'

services:
  lambda:
    build: ./lambda
    volumes:
      - ./lambda:/app

  node-example:
    build: ./node-example
    environment:
      PORT: 3000
    ports:
      - 3000:3000
    volumes:
      - ${AWS_CREDENTIALS_PATH}:/root/.aws
      - ./node-example:/app

  state:
    build:
      args:
        TERRAFORM_VERSION: ${TERRAFORM_VERSION}
      context: ./state
    volumes:
      - ${AWS_CREDENTIALS_PATH}:/root/.aws

  terraform:
    build:
      args:
        FOLDER: ${FOLDER}
        TERRAFORM_VERSION: ${TERRAFORM_VERSION}
      context: .
    volumes:
      - ${AWS_CREDENTIALS_PATH}:/root/.aws
