version: '3.7'

services:
  aws:
    image: amazon/aws-cli:latest
    volumes:
      - ~./Owner/.aws:/root/.aws
  terraform:
    build:
      args:
        TERRAFORM_VERSION: ${TERRAFORM_VERSION}
      context: .
