version: '3.7'

services:
  pline:
    build:
      args:
        TERRAFORM_VERSION: ${TERRAFORM_VERSION}
      context: .
    volumes:
      - ${AWS_CREDENTIALS_PATH}:/root/.aws
      - /var/run/docker.sock:/var/run/docker.sock
